### ISSUE TITLE
please update the SPARQL endpoint URL

### ISSUE THREAD

**Issue by egonw** [dbcls/LinkedData-Agora#153]
Hi awesome people, our WikiPathways SPARQL end point has been down due to security measures taken by Maastricht University after the ransom attack. We have now put up a replacement server. It's configuration is not identical, but the data is. So, the score won't go up completely. As part of this the URL has slightly changed. This may be temporary, or permanent, that is not clear at this moment. 

Please update the endpoint URL to: http://sparql.wikipathways.org/sparql

**Comment by yayamamo** [comment]
Sorry to hear the incident and for our late action, but now we've changed the URL.

**Comment by egonw** [comment]
Thanks, twice!

**Comment by egonw** [comment]
@yayamamo, did the URL also get changed in the tests? I see it is changed in the `Basic Information`:

![image](https://user-images.githubusercontent.com/26721/72927532-b74d4e00-3d56-11ea-8868-b6f8225253af.png)

But from with test logs, I get the impression those still use the old URL.

**Comment by yayamamo** [comment]
Yes, the crawler takes a long time to gather required data from some endpoints for some reasons we are investigating, and UmakaYummy hasn't updated the result page. Since the latest WikiPathways has already been crawled, you can check it at the following URL: https://yummydata.org/endpoint/18?date=2020-01-20 .
